## Importação de bibliotecas principais

In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", 70)

In [3]:
df_sheet_names = pd.ExcelFile(
    "../data/raw/desastres-naturais-atlas-digital.xlsx"
).sheet_names

### Importação dataset + EDA inicial

In [4]:
SHEET_NAMES = [
    "Atlas Valores Originais",
    "Cálculo Correção",
    "Atlas Valores Corrigidos",
    "Grupos de Desastres",
]

In [5]:
df_desastres = pd.read_excel(
    "../data/raw/desastres-naturais-atlas-digital.xlsx", sheet_name=SHEET_NAMES[2]
)

In [6]:
df_desastres.head()

,Protocolo_S2iD,Nome_Municipio,Sigla_UF,regiao,Data_Registro,Data_Evento,Cod_Cobrade,tipologia,descricao_tipologia,grupo_de_desastre,Cod_IBGE_Mun,Setores Censitários,Status,DH_Descricao,DH_MORTOS,DH_FERIDOS,DH_ENFERMOS,DH_DESABRIGADOS,DH_DESALOJADOS,DH_DESAPARECIDOS,DH_AFETADOS_SECA_ESTIAGEM,DH_total_danos_humanos_diretos,DH_OUTROS AFETADOS,DM_Descricao,DM_Uni Habita Danificadas,DM_Uni Habita Destruidas,DM_Uni Habita Valor,DM_Inst Saúde Danificadas,DM_Inst Saúde Destruidas,DM_Inst Saúde Valor,DM_Inst Ensino Danificadas,DM_Inst Ensino Destruidas,DM_Inst Ensino Valor,DM_Inst Serviços Danificadas,DM_Inst Serviços Destruidas,DM_Inst Serviços Valor,DM_Inst Comuni Danificadas,DM_Inst Comuni Destruidas,DM_Inst Comuni Valor,DM_Obras de Infra Danificadas,DM_Obras de Infra Destruidas,DM_Obras de Infra Valor,DM_total_danos_materiais,DA_Descricao,DA_Polui/cont da água,DA_Polui/cont do ar,DA_Polui/cont do solo,DA_Dimi/exauri hídrico,DA_Incêndi parques/APA's/APP's,PEPL_Descricao,PEPL_Assis_méd e emergên(R$),PEPL_Abast de água pot(R$),PEPL_sist de esgotos sanit(R$),PEPL_Sis limp e rec lixo (R$),PEPL_Sis cont pragas (R$),PEPL_distrib energia (R$),PEPL_Telecomunicações (R$),PEPL_Tran loc/reg/l_curso (R$),PEPL_Distrib combustíveis(R$),PEPL_Segurança pública (R$),PEPL_Ensino (R$),PEPL_total_publico,PEPR_Descricao,PEPR_Agricultura (R$),PEPR_Pecuária (R$),PEPR_Indústria (R$),PEPR_Comércio (R$),PEPR_Serviços (R$),PEPR_total_privado,PE_PLePR
0,SC-D-4215406-14110-19910107,Salto Veloso,SC,Sul,1991-01-07,1991-01-07,14110,4,Estiagem e Seca,Climatológico,4215406,NaN,Registro,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0.0,0.0,0,0.0,0.0,0,0.0,0,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,RS-D-4313102-14110-19910112,Nova Palma,RS,Sul,1991-01-12,1991-01-12,14110,4,Estiagem e Seca,Climatológico,4313102,NaN,Registro,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0.0,0.0,0,0.0,0.0,0,0.0,0,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,RS-D-4304952-14110-19910115,Caseiros,RS,Sul,1991-01-15,1991-01-15,14110,4,Estiagem e Seca,Climatológico,4304952,NaN,Registro,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0.0,0.0,0,0.0,0.0,0,0.0,0,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,SC-D-4208609-14110-19910115,Jaborá,SC,Sul,1991-01-15,1991-01-15,14110,4,Estiagem e Seca,Climatológico,4208609,NaN,Registro,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0.0,0.0,0,0.0,0.0,0,0.0,0,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,SC-D-4207650-14110-19910118,Iporã do Oeste,SC,Sul,1991-01-18,1991-01-18,14110,4,Estiagem e Seca,Climatológico,4207650,NaN,Registro,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0.0,0.0,0,0.0,0.0,0,0.0,0,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df_desastres.info()

<class 'pandas.DataFrame'>
RangeIndex: 71929 entries, 0 to 71928
Data columns (total 70 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Protocolo_S2iD                  71929 non-null  str
 1   Nome_Municipio                  71929 non-null  str
 2   Sigla_UF                        71929 non-null  str
 3   regiao                          71929 non-null  str
 4   Data_Registro                   71929 non-null  datetime64[us]
 5   Data_Evento                     71929 non-null  datetime64[us]
 6   Cod_Cobrade                     71929 non-null  int64
 7   tipologia                       71929 non-null  int64
 8   descricao_tipologia             71929 non-null  str
 9   grupo_de_desastre               71929 non-null  str
 10  Cod_IBGE_Mun                    71929 non-null  int64
 11  Setores Censitários             25715 non-null  str
 12  Status                          71929 non-null  str
 13  DH_Descricao                    29468 non-null  str
 14  DH_MORTOS                       71929 non-null  int64
 15  DH_FERIDOS                      71929 non-null  int64
 16  DH_ENFERMOS                     71929 non-null  int64
 17  DH_DESABRIGADOS                 71929 non-null  int64
 18  DH_DESALOJADOS                  71929 non-null  int64
 19  DH_DESAPARECIDOS                71929 non-null  int64
 20  DH_AFETADOS_SECA_ESTIAGEM       71929 non-null  int64
 21  DH_total_danos_humanos_diretos  71929 non-null  int64
 22  DH_OUTROS AFETADOS              71929 non-null  int64
 23  DM_Descricao                    22143 non-null  str
 24  DM_Uni Habita Danificadas       71929 non-null  int64
 25  DM_Uni Habita Destruidas        71929 non-null  int64
 26  DM_Uni Habita Valor             71929 non-null  float64
 27  DM_Inst Saúde Danificadas       71929 non-null  float64
 28  DM_Inst Saúde Destruidas        71929 non-null  int64
 29  DM_Inst Saúde Valor             71929 non-null  float64
 30  DM_Inst Ensino Danificadas      71929 non-null  float64
 31  DM_Inst Ensino Destruidas       71929 non-null  int64
 32  DM_Inst Ensino Valor            71929 non-null  float64
 33  DM_Inst Serviços Danificadas    71929 non-null  int64
 34  DM_Inst Serviços Destruidas     71929 non-null  int64
 35  DM_Inst Serviços Valor          71929 non-null  float64
 36  DM_Inst Comuni Danificadas      71929 non-null  int64
 37  DM_Inst Comuni Destruidas       71929 non-null  int64
 38  DM_Inst Comuni Valor            71929 non-null  float64
 39  DM_Obras de Infra Danificadas   71929 non-null  float64
 40  DM_Obras de Infra Destruidas    71929 non-null  float64
 41  DM_Obras de Infra Valor         71929 non-null  float64
 42  DM_total_danos_materiais        71929 non-null  float64
 43  DA_Descricao                    22904 non-null  str
 44  DA_Polui/cont da água           1834 non-null   str
 45  DA_Polui/cont do ar             1139 non-null   str
 46  DA_Polui/cont do solo           984 non-null    str
 47  DA_Dimi/exauri hídrico          3020 non-null   str
 48  DA_Incêndi parques/APA's/APP's  2064 non-null   str
 49  PEPL_Descricao                  24754 non-null  str
 50  PEPL_Assis_méd e emergên(R$)    71929 non-null  float64
 51  PEPL_Abast de água pot(R$)      71929 non-null  float64
 52  PEPL_sist de esgotos sanit(R$)  71929 non-null  float64
 53  PEPL_Sis limp e rec lixo (R$)   71929 non-null  float64
 54  PEPL_Sis cont pragas (R$)       71929 non-null  float64
 55  PEPL_distrib energia (R$)       71929 non-null  float64
 56  PEPL_Telecomunicações (R$)      71929 non-null  float64
 57  PEPL_Tran loc/reg/l_curso (R$)  71929 non-null  float64
 58  PEPL_Distrib combustíveis(R$)   71929 non-null  float64
 59  PEPL_Segurança pública (R$)     71929 non-null  float64
 60  PEPL_Ensino (R$)                71929 non-null  float64
 61  PEPL_total_publico              71929 non-null  float64
 62  PEPR_Descricao                  26708 non-null  str
 63  PEPR_Agricultura (R$)           71929 non-null  float64
 64  PEPR_Pecuária (R$)              71929 non-null  float64
 65  PEPR_Indústria (R$)             71929 non-null  float64
 66  PEPR_Comércio (R$)              71929 non-null  float64
 67  PEPR_Serviços (R$)              71929 non-null  float64
 68  PEPR_total_privado              71929 non-null  float64
 69  PE_PLePR                        71929 non-null  float64
dtypes: datetime64[us](2), float64(30), int64(20), str(18)
memory usage: 96.2 MB

In [8]:
df_desastres.sample(4)

,Protocolo_S2iD,Nome_Municipio,Sigla_UF,regiao,Data_Registro,Data_Evento,Cod_Cobrade,tipologia,descricao_tipologia,grupo_de_desastre,Cod_IBGE_Mun,Setores Censitários,Status,DH_Descricao,DH_MORTOS,DH_FERIDOS,DH_ENFERMOS,DH_DESABRIGADOS,DH_DESALOJADOS,DH_DESAPARECIDOS,DH_AFETADOS_SECA_ESTIAGEM,DH_total_danos_humanos_diretos,DH_OUTROS AFETADOS,DM_Descricao,DM_Uni Habita Danificadas,DM_Uni Habita Destruidas,DM_Uni Habita Valor,DM_Inst Saúde Danificadas,DM_Inst Saúde Destruidas,DM_Inst Saúde Valor,DM_Inst Ensino Danificadas,DM_Inst Ensino Destruidas,DM_Inst Ensino Valor,DM_Inst Serviços Danificadas,DM_Inst Serviços Destruidas,DM_Inst Serviços Valor,DM_Inst Comuni Danificadas,DM_Inst Comuni Destruidas,DM_Inst Comuni Valor,DM_Obras de Infra Danificadas,DM_Obras de Infra Destruidas,DM_Obras de Infra Valor,DM_total_danos_materiais,DA_Descricao,DA_Polui/cont da água,DA_Polui/cont do ar,DA_Polui/cont do solo,DA_Dimi/exauri hídrico,DA_Incêndi parques/APA's/APP's,PEPL_Descricao,PEPL_Assis_méd e emergên(R$),PEPL_Abast de água pot(R$),PEPL_sist de esgotos sanit(R$),PEPL_Sis limp e rec lixo (R$),PEPL_Sis cont pragas (R$),PEPL_distrib energia (R$),PEPL_Telecomunicações (R$),PEPL_Tran loc/reg/l_curso (R$),PEPL_Distrib combustíveis(R$),PEPL_Segurança pública (R$),PEPL_Ensino (R$),PEPL_total_publico,PEPR_Descricao,PEPR_Agricultura (R$),PEPR_Pecuária (R$),PEPR_Indústria (R$),PEPR_Comércio (R$),PEPR_Serviços (R$),PEPR_total_privado,PE_PLePR
45899,SP-F-3543907-23120-20180513,Rio Claro,SP,Sudeste,2018-05-18 13:50:47,2018-05-13,23120,14,Outros,Outros,3543907,354390705000085,Registro,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0.000000,0.0,0,0.0,0.0,0,0.0,0,0,0.0,0,0,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,Muita fumaça produzida pelo fogo em mato.,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,NaN,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000e+00,0.000000e+00
6432,PI-P-2209401-14110-19990927,Santo Antônio de Lisboa,PI,Nordeste,1999-09-27 00:00:00,1999-09-27,14110,4,Estiagem e Seca,Climatológico,2209401,NaN,Registro,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0.000000,0.0,0,0.0,0.0,0,0.0,0,0,0.0,0,0,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,NaN,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000e+00,0.000000e+00
62944,MG-F-3158805-13214-20230212,Santana do Jacaré,MG,Sudeste,2023-02-13 12:38:49,2023-02-12,13214,13,Chuvas Intensas,Hidrológico,3158805,"315880505000003, 315880505000001, 315880505000...",Registro,Chuva rápida que ultrapassou 60mm e atingiu o ...,0,0,0,0,0,0,0,0,18,"Unidades habitacionais inundadas, com perda e ...",0,1,12823.480993,0.0,4,0.0,0.0,0,0.0,0,0,0.0,0,0,8548.987328,0.0,0.0,0.000000e+00,2.137247e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,NaN,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000e+00,0.000000e+00
23851,CE-A-2300309-12100-20090511,Acopiara,CE,Nordeste,2009-05-11 00:00:00,2009-05-11,12100,7,Inundações,Hidrológico,2300309,NaN,Reconhecido,NaN,0,0,0,10,135,0,0,145,8616,NaN,28,2,310766.260633,0.0,0,0.0,0.0,0,0.0,0,0,0.0,0,0,0.000000,52.0,68.0,6.825708e+06,7.136474e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,462590.998652,462590.998652,NaN,1.405268e+07,960765.920278,0.0,0.0,0.0,1.501345e+07,1.547604e+07

In [9]:
# df_desastres = df_desastres[df_desastres["Data_Evento"].dt.year >= 2000]
columns_to_drop = [
    "Protocolo_S2iD",
    "Cod_Cobrade",
    "Cod_IBGE_Mun",
    "Setores Censitários",
]

#### Analise da colunas categoricas

In [10]:
df_desastres_cat = df_desastres.select_dtypes(include="str")

In [11]:
df_desastres_cat.info()

<class 'pandas.DataFrame'>
RangeIndex: 71929 entries, 0 to 71928
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Protocolo_S2iD                  71929 non-null  str
 1   Nome_Municipio                  71929 non-null  str
 2   Sigla_UF                        71929 non-null  str
 3   regiao                          71929 non-null  str
 4   descricao_tipologia             71929 non-null  str
 5   grupo_de_desastre               71929 non-null  str
 6   Setores Censitários             25715 non-null  str
 7   Status                          71929 non-null  str
 8   DH_Descricao                    29468 non-null  str
 9   DM_Descricao                    22143 non-null  str
 10  DA_Descricao                    22904 non-null  str
 11  DA_Polui/cont da água           1834 non-null   str
 12  DA_Polui/cont do ar             1139 non-null   str
 13  DA_Polui/cont do solo           984 non-null    str
 14  DA_Dimi/exauri hídrico          3020 non-null   str
 15  DA_Incêndi parques/APA's/APP's  2064 non-null   str
 16  PEPL_Descricao                  24754 non-null  str
 17  PEPR_Descricao                  26708 non-null  str
dtypes: str(18)
memory usage: 67.6 MB

In [ ]:
df_desastres_cat[df_desastres_cat.isna().any(axis=1)]